In [4]:
import qutip as qu
import numpy as np
seed = 1
np.random.seed(seed=seed)

In [7]:
import numpy as np
from scipy.constants import pi

In [8]:
from qutip.tensor import tensor
from qutip.states import *
from qutip.operators import *
final_states = []
for i in range(1000):
    final_states.append(qu.tensor([qu.rand_ket(2), qu.rand_ket(2), qu.rand_ket(2)]))

In [9]:
def rand_ghz():
    delta = np.random.uniform(low=0, high=pi/4 )
    alpha = np.random.uniform(low=0, high=pi/2 )
    beta = np.random.uniform(low=0, high=pi/2 )
    gamma = np.random.uniform(low=0, high=pi/2 )
    phi = np.random.uniform(low=0, high=2*pi )
    K = 1/(1 + np.cos(delta)*np.sin(delta)*np.cos(alpha)*np.cos(beta)*np.cos(phi))

    phi_a = np.cos(alpha)*basis(2,0) + np.sin(alpha)*basis(2,1)
    phi_b = np.cos(beta)*basis(2,0) + np.sin(beta)*basis(2,1)
    phi_c = np.cos(gamma)*basis(2,0) + np.sin(gamma)*basis(2,1)

    psi_ghz = np.sqrt(K)*(np.cos(gamma)*tensor([basis(2,0)]*3) +np.sin(delta)*np.exp(gamma*1j)*tensor([phi_a,phi_b, phi_c]))
    return psi_ghz

In [10]:
random_ghz = []
for i in range(1000):
    random_ghz.append(rand_ghz())

In [11]:
aux = random_ghz[0]

In [12]:
real = np.real(np.array(aux).flatten())
print(real)
imag = np.imag(np.array(aux).flatten())
print(imag)
vec = np.zeros(len(real)*2)
vec[::2] = real
vec[1::2] = imag
np.append(vec, 1)

[0.60029049 0.18107015 0.02157945 0.03298391 0.08684367 0.13273941
 0.01581952 0.02417993]
[0.18107015 0.27676334 0.03298391 0.05041547 0.13273941 0.20289043
 0.02417993 0.03695871]


array([0.60029049, 0.18107015, 0.18107015, 0.27676334, 0.02157945,
       0.03298391, 0.03298391, 0.05041547, 0.08684367, 0.13273941,
       0.13273941, 0.20289043, 0.01581952, 0.02417993, 0.02417993,
       0.03695871, 1.        ])

In [13]:
flatten_ghz = []
for i in random_ghz:
    aux = i
    vec = np.zeros(len(real)*2)
    vec[::2] = np.real(np.array(aux).flatten())
    vec[1::2] = np.imag(np.array(aux).flatten())
    flatten_ghz.append(np.append(vec, int(1)))

flatten_separable = []
for i in final_states:
    aux = i
    vec = np.zeros(len(real)*2)
    vec[::2] = np.real(np.array(aux).flatten())
    vec[1::2] = np.imag(np.array(aux).flatten())
    flatten_separable.append(np.append(vec, int(0)))



In [14]:
flatten_ghz

[array([0.60029049, 0.18107015, 0.18107015, 0.27676334, 0.02157945,
        0.03298391, 0.03298391, 0.05041547, 0.08684367, 0.13273941,
        0.13273941, 0.20289043, 0.01581952, 0.02417993, 0.02417993,
        0.03695871, 1.        ]),
 array([1.04204534e+00, 3.24443690e-03, 3.24443690e-03, 2.17499342e-04,
        3.40325011e-03, 2.28145802e-04, 2.28145802e-04, 1.52943525e-05,
        1.65114763e-01, 1.10689014e-02, 1.10689014e-02, 7.42032854e-04,
        1.16107174e-02, 7.78354908e-04, 7.78354908e-04, 5.21790639e-05,
        1.00000000e+00]),
 array([0.90048998, 0.0547772 , 0.0547772 , 0.03589142, 0.14270096,
        0.09350131, 0.09350131, 0.06126444, 0.08090656, 0.05301204,
        0.05301204, 0.03473484, 0.13810252, 0.09048829, 0.09048829,
        0.05929024, 1.        ]),
 array([0.59470732, 0.03941021, 0.03941021, 0.05616156, 0.01378126,
        0.019639  , 0.019639  , 0.02798658, 0.09445134, 0.13459797,
        0.13459797, 0.19180898, 0.04706725, 0.06707323, 0.06707323,
      

In [15]:
flatten_separable

[array([ 0.07561638,  0.15730715,  0.15054344, -0.16417308,  0.01140964,
         0.14624877,  0.16787955, -0.08285264, -0.05250604, -0.43556332,
        -0.49120237,  0.2687053 ,  0.09131619, -0.35724076, -0.4665819 ,
         0.06116077,  0.        ]),
 array([-0.08836294,  0.13796247, -0.04191611, -0.0983452 ,  0.38904471,
         0.14546458, -0.22140513,  0.15631428, -0.21960088,  0.13916425,
         0.0056649 , -0.16954986,  0.46198236,  0.47009822, -0.42325046,
         0.07634145,  0.        ]),
 array([-0.17761491,  0.41454335, -0.20636657, -0.11706888, -0.13440663,
        -0.2700355 ,  0.14903211, -0.0545048 ,  0.17978298, -0.5526649 ,
         0.27845473,  0.12626749,  0.20387533,  0.33094699, -0.1849351 ,
         0.08726877,  0.        ]),
 array([-0.16345905,  0.05701041, -0.16589975, -0.03548773,  0.11565797,
         0.02627345,  0.08346926,  0.08088763, -0.55612865, -0.08890778,
        -0.42040791, -0.35760119,  0.29072462,  0.2536944 ,  0.11426984,
         0.36045

In [16]:
import pandas as pd

In [17]:
df_sep = pd.DataFrame(flatten_separable)
df_sep = df_sep.rename(columns={16: 'entangled',})
df_sep

df_ghz = pd.DataFrame(flatten_ghz)
df_ghz = df_ghz.rename(columns={16: 'entangled',})
df_ghz


0         1         2         3         4         5         6  \
0    0.600290  0.181070  0.181070  0.276763  0.021579  0.032984  0.032984   
1    1.042045  0.003244  0.003244  0.000217  0.003403  0.000228  0.000228   
2    0.900490  0.054777  0.054777  0.035891  0.142701  0.093501  0.093501   
3    0.594707  0.039410  0.039410  0.056162  0.013781  0.019639  0.019639   
4    0.820390  0.148390  0.148390  0.134447  0.069301  0.062790  0.062790   
..        ...       ...       ...       ...       ...       ...       ...   
995  1.135609  0.070032  0.070032  0.025218  0.535893  0.192973  0.192973   
996  1.079065  0.141917  0.141917  0.111845  0.147395  0.116162  0.116162   
997  0.948740  0.013765  0.013765  0.006492  0.006703  0.003161  0.003161   
998  0.847486  0.174455  0.174455  0.225419  0.108692  0.140444  0.140444   
999  0.585964  0.006112  0.006112  0.008485  0.001711  0.002375  0.002375   

            7         8         9        10        11        12        13  \
0    0.050415  0.086844  0.132739  0.132739  0.202890  0.015820  0.024180   
1    0.000015  0.165115  0.011069  0.011069  0.000742  0.011611  0.000778   
2    0.061264  0.080907  0.053012  0.053012  0.034735  0.138103  0.090488   
3    0.027987  0.094451  0.134598  0.134598  0.191809  0.047067  0.067073   
4    0.056890  0.154953  0.140394  0.140394  0.127202  0.065567  0.059406   
..        ...       ...       ...       ...       ...       ...       ...   
995  0.069489  0.085551  0.030807  0.030807  0.011093  0.235737  0.084888   
996  0.091548  0.000763  0.000601  0.000601  0.000474  0.000625  0.000492   
997  0.001491  0.045157  0.021297  0.021297  0.010044  0.010371  0.004891   
998  0.181472  0.034415  0.044469  0.044469  0.057460  0.027706  0.035799   
999  0.003297  0.186094  0.258354  0.258354  0.358672  0.072303  0.100378   

           14        15  entangled  
0    0.024180  0.036959        1.0  
1    0.000778  0.000052        1.0  
2    0.090488  0.059290        1.0  
3    0.067073  0.095583        1.0  
4    0.059406  0.053825        1.0  
..        ...       ...        ...  
995  0.084888  0.030568        1.0  
996  0.000492  0.000388        1.0  
997  0.004891  0.002307        1.0  
998  0.035799  0.046258        1.0  
999  0.100378  0.139355        1.0  

[1000 rows x 17 columns]

In [18]:
df = pd.concat([df_sep, df_ghz])
df = df.sample(frac=1, ignore_index=True, random_state=1)
df.head()


0         1         2         3         4         5         6  \
0  0.113325  0.043924  0.013853 -0.101828  0.306383 -0.055935 -0.106208   
1  1.184758  0.184784  0.184784  0.109123  0.252158  0.148910  0.148910   
2  0.477289  0.015307  0.015307  0.028522  0.133023  0.247864  0.247864   
3  1.133226  0.059274  0.059274  0.018779  0.201729  0.063911  0.063911   
4  1.339046  0.090978  0.090978  0.029427  0.405802  0.131255  0.131255   

          7         8         9        10        11        12        13  \
0 -0.240972  0.117857  0.220008  0.157771 -0.140158  0.552257  0.322585   
1  0.087938  0.209068  0.123463  0.123463  0.072910  0.168479  0.099494   
2  0.461847  0.000336  0.000627  0.000627  0.001168  0.005447  0.010150   
3  0.020248  0.149464  0.047353  0.047353  0.015002  0.161158  0.051058   
4  0.042454  0.069769  0.022567  0.022567  0.007299  0.100657  0.032557   

         14        15  entangled  
0  0.156763 -0.517559        0.0  
1  0.099494  0.058755        1.0  
2  0.010150  0.018913        1.0  
3  0.051058  0.016176        1.0  
4  0.032557  0.010530        1.0

In [19]:
import joblib
joblib.dump(df, "ghz+sep.job")

['ghz+sep.job']